### PR TITLE
Fix sql queries

### LINKED ISSUE #2338: Migration errors with new sqlx version
@klochowicz : did you run the migration when merging this PR? Looks like we get errors when running migration since this PR: 

```
╰ ./prepare_db.sh
Applied 20210903050345/migrate create cfd and order tables (62.936154ms)
Applied 20211025050345/migrate rename term to settlement time interval (1.782077ms)
Applied 20211207035936/migrate add-fee-to-order (651.475µs)
Applied 20211208000000/migrate associate counterpart identity with cfd (5.464037ms)
Applied 20211210000000/migrate remove-order-from-database (1.242287ms)
Applied 20211213000000/migrate remove-oracle event id from cfd (732.646µs)
Applied 20211214055426/migrate replace-origin-with-role (621.597µs)
Applied 20211220000000/migrate introduce-event-sourcing (1.013698ms)
Applied 20220121052945/migrate add opening fee (498.827µs)
Applied 20220124063030/migrate add initial funding rate (706.875µs)
Applied 20220125051124/migrate add initial tx fee rate (591.321µs)
Applied 20220404113202/migrate create closed cfds tables (32.344378ms)
Applied 20220428103201/migrate create failed cfds table (32.142125ms)
Applied 20220502172229/migrate create time to first position table (33.394799ms)
Applied 20220516000538/migrate counterparty peer id (42.749273ms)
Applied 20220525225235/migrate rename tables (45.511744ms)
Applied 20220526225235/migrate rollover-completed-table (32.92339ms)
Applied 20220622041906/migrate add settlement event id to revoke commit transactions (12.677079ms)
Applied 20220622055305/migrate add complete fee to rollover tables (14.398834ms)
   Compiling model v0.1.0 (/Users/bonomat/src/github/comit/hermes/model)
   Compiling sqlite-db v0.1.0 (/Users/bonomat/src/github/comit/hermes/sqlite-db)
error[E0308]: mismatched types
   --> sqlite-db/src/closed.rs:854:15
    |
854 |       let row = sqlx::query_as!(
    |  _______________^
855 | |         models::Settlement::Cet,
856 | |         r#"
857 | |         SELECT
...   |
872 | |         id
873 | |     )
    | |_____^ expected struct `models::Txid`, found enum `std::option::Option`
    |
    = note: expected struct `models::Txid`
                 found enum `std::option::Option<models::Txid>`
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> sqlite-db/src/closed.rs:886:15
    |
886 |       let row = sqlx::query_as!(
    |  _______________^
887 | |         models::Settlement::Refund,
888 | |         r#"
889 | |         SELECT
...   |
903 | |         id
904 | |     )
    | |_____^ expected struct `models::Txid`, found enum `std::option::Option`
    |
    = note: expected struct `models::Txid`
                 found enum `std::option::Option<models::Txid>`
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> sqlite-db/src/closed.rs:976:23
    |
976 |     Ok(Timestamp::new(row.created_at))
    |                       ^^^^^^^^^^^^^^ expected `i64`, found enum `std::option::Option`
    |
    = note: expected type `i64`
               found enum `std::option::Option<i64>`

error[E0308]: mismatched types
   --> sqlite-db/src/failed.rs:314:23
    |
314 |     Ok(Timestamp::new(row.created_at))
    |                       ^^^^^^^^^^^^^^ expected `i64`, found enum `std::option::Option`
    |
    = note: expected type `i64`
               found enum `std::option::Option<i64>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `sqlite-db` due to 4 previous errors
error: `cargo check` failed with status: exit status: 101
```

_Originally posted by @bonomat in https://github.com/itchysats/itchysats/issues/2256#issuecomment-1171954182_

### PR DESCRIPTION
**Pull request by bonomat**
There was a problem introduced in #2256 . Ideally we run `cargo sqlx prepare --check` during CI but I couldn't get it working yet.

### CODE REVIEW

**Comment by klochowicz** [comment]
> There was a problem introduced in #2256 . Ideally we run `cargo sqlx prepare --check` during CI but I couldn't get it working yet.

as a stopgap, perhaps we could put a comment next to the dependency in `Cargo.toml` to run this command whenever updating sqlx?

File: Cargo.toml [hunk 1]
```diff
@@ -26,3 +26,6 @@ xtra = { git = "https://github.com/comit-network/xtra" } # We need to use unrele
 maia = { git = "https://github.com/comit-network/maia", rev = "fc6b78b98407b10b55f8cfd152062ad77f98cd9f" } # Unreleased
 maia-core = { git = "https://github.com/comit-network/maia", tag = "0.1.1", package = "maia-core" } # Pinned to support maia 0.1 and 0.2
 xtra_productivity = { git = "https://github.com/comit-network/xtra-productivity" } # Unreleased
+
+[profile.dev.package.sqlx-macros]
+opt-level = 3
```
Comment (klochowicz) [inline Cargo.toml:31]: nice!

**Review by klochowicz — APPROVED** [review]
thanks for spotting and addressing it so quickly! I have created a ticket as I wasn't sure whether you're working on it, but noticed the PR incoming as I was only browsing the recent docs.

**Comment by klochowicz** [comment]
merging after running it locally and verifying that it works. 

bors r+
